image: maven:3-jdk-8

.caching: &caching
  before_script:
   - cp -r .m2 /root/ || true

  after_script:
   - cp -r /root/.m2 .
   - cp src/ear/target/eaas-server.ear .
  
standalone-server-build:
  <<: *caching
  script:
    - mvn -f src/pom.xml clean install
    - docsrc="${PWD}/src/emil/target/apidocs"

    # Prepare SSH for working with Git repositories
    - which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh && eval $(ssh-agent -s)
    - echo "${EAAS_API_DOCS_SSHKEY}" | tr -d '\r' | ssh-add -
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts

    # Clone docs repository and update it with generated pages
    - docdir="/tmp/eaas-api-docs"
    - doctgt="${docdir}/public/${CI_COMMIT_REF_NAME}"
    - mkdir -p "${docdir}" && cd "${docdir}" && git clone git@gitlab.com:openslx/eaas-api-docs.git .
    - mkdir -p "${doctgt}" && rm -r -v ${doctgt}/* || true
    - cp -r -v ${docsrc}/* "${doctgt}"

    # Finally, commit and push new pages...
    - git config --local user.email "nobody@openslx.com"
    - git config --local user.name "eaas-server-ci"
    - git add public/
    - git commit -m "Update triggered by pipeline ${CI_PIPELINE_URL}" || true
    - git push origin master

  artifacts:
    paths:
    - eaas-server.ear
  cache:
    paths:
    - .m2 
    
emucomp-build:
  <<: *caching
  script:
    - ln -fs deployment-emucomp.xml src/ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f src/pom.xml clean install -P emucomp,imagearchive -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
gateway-build:
  <<: *caching
  script: 
    - ln -fs deployment-gateway.xml src/ear/src/main/application/META-INF/jboss-deployment-structure.xml
    - mvn -f src/pom.xml clean install -P '!emucomp' -pl ear -am
  artifacts:
   paths:
    - eaas-server.ear
  cache:
   paths:
    - .m2
    
trigger:
  stage: deploy
  script:
   - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/11165186/trigger/pipeline
  only:
   refs:
     - master
   variables:
     - $CI_PROJECT_NAMESPACE == "openslx"

deploy-citar:
 stage: deploy
 before_script:
  - apt-get update -qq && apt-get install -y rsync sshpass
 script:
  - sshpass -p $gitlab rsync -e "ssh -o StrictHostKeyChecking=no" -rltvz -O src/ear/target/eaas-server.ear gitlab@192.52.32.102:/mnt/data/citar-demo/deployments/eaas-server.ear
  - sshpass -p $gitlab ssh gitlab@192.52.32.102 'sudo systemctl restart eaas'
 only:
  refs:
   - citar-release