//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 02:34:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nationalarchives.gov.uk/pronom/SignatureFile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pronom.nationalarchives.gov.xsd;