///*
// * This file is part of the Emulation-as-a-Service framework.
// *
// * The Emulation-as-a-Service framework is free software: you can
// * redistribute it and/or modify it under the terms of the GNU General
// * Public License as published by the Free Software Foundation, either
// * version 3 of the License, or (at your option) any later version.
// *
// * The Emulation-as-a-Service framework is distributed in the hope that
// * it will be useful, but WITHOUT ANY WARRANTY; without even the
// * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// * PARTICULAR PURPOSE.  See the GNU General Public License for
// * more details.
// *
// * You should have received a copy of the GNU General Public License
// * along with the Emulation-as-a-Software framework.
// * If not, see <http://www.gnu.org/licenses/>.
// */
//
////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//// Any modifications to this file will be lost upon recompilation of the source schema. 
//// Generated on: 2014.05.09 at 04:38:52 PM CEST 
////
//
//
//package de.bwl.bwfla.common.datatypes;
//
//import java.io.StringReader;
//import java.util.ArrayList;
//import java.util.List;
//import javax.xml.bind.JAXBContext;
//import javax.xml.bind.JAXBElement;
//import javax.xml.bind.JAXBException;
//import javax.xml.bind.Unmarshaller;
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlRootElement;
//import javax.xml.bind.annotation.XmlType;
//import javax.xml.transform.stream.StreamSource;
//
//import de.bwl.bwfla.emucomp.api.Environment;
//
//
///**
// * <p>Java class for networkEnvironment complex type.
// * 
// * <p>The following schema fragment specifies the expected content contained within this class.
// * 
// * <pre>
// * &lt;complexType name="networkEnvironment">
// *   &lt;complexContent>
// *     &lt;extension base="{http://bwfla.bwl.de/common/datatypes}environment">
// *       &lt;sequence>
// *         &lt;element name="network" type="{http://bwfla.bwl.de/common/datatypes}network" maxOccurs="unbounded"/>
// *       &lt;/sequence>
// *     &lt;/extension>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// * 
// * 
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "networkEnvironment", NAMESPACE = "http://bwfla.bwl.de/common/datatypes", propOrder = {
//    "network"
//})
//@XmlRootElement(NAMESPACE = "http://bwfla.bwl.de/common/datatypes")
//public class NetworkEnvironment
//    extends Environment
//{
//
//    @XmlElement(NAMESPACE = "http://bwfla.bwl.de/common/datatypes", required = true)
//    protected List<Network> network;
//
//    /**
//     * Gets the value of the network property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the network property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getNetwork().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link Network }
//     * 
//     * 
//     */
//    public List<Network> getNetwork() {
//        if (network == null) {
//            network = new ArrayList<Network>();
//        }
//        return this.network;
//    }
//
//    public static NetworkEnvironment fromValue(String data) throws JAXBException {
//    	JAXBContext jc = JAXBContext.newInstance(NetworkEnvironment.class);
//    	Unmarshaller unmarshaller = jc.createUnmarshaller();
//    	JAXBElement<NetworkEnvironment> elem = unmarshaller.unmarshal(new StreamSource(new StringReader(data)), NetworkEnvironment.class);
//    	return elem.getValue();
//    }
//}
